Repository ponylang/release-bot-action, pull requests merged in 2020-08, with the labels that each got.

#9 Add support for adding release notes as part of the release process
  scripts/announce-a-release.bash
Labels: changelog - added

#10 Make .release-notes support optional
  scripts/announce-a-release.bash
Labels: changelog - fixed

#11 Make ASSET_NAME hardcoded
  README.md
  scripts/announce-a-release.bash
Labels: changelog - changed

#12 Remove empty line in Last Week in Pony announcement
  scripts/announce-a-release.bash
Labels: changelog - changed

#25 Fix broken trigger-release-announcement step
  .release-notes/tra-compilation.md
  scripts/trigger-release-announcement.bash
Labels: changelog - fixed

#24 Allow for setting the default branch
  .release-notes/24.md
  README.md
  RELEASE_PROCESS.md
  action.yml
  scripts/announce-a-release.bash
  scripts/start-a-release.bash
  scripts/trigger-release-announcement.bash
Labels: changelog - changed
